language: ruby
rvm:
 - 2.5.1
 - jruby
services:
  - postgresql
addons:
  postgresql: "10"
env:
  global:
  - PGPORT=5433
before_script:
  - cp config/database.yml.travis config/database.yml
script:
  - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
  - bundle exec rspec
